### ISSUE TITLE
Problème de push sur Clever Cloud à l'init de projet

### ISSUE THREAD

**Issue by rguillome** [DiginamicFormation/atelier-starter#4]
Sur les applications back, à l'initialisation le stage deploy de Jenkins échoue car on est déphasé avec le changement de dépot Git (le dépot CleverCloud est toujours sur l'history du dépôt GitHub de la session précédente)

Contournement : 
1. faire un ```git push -p``` sur le step de déploiement vers Clever Cloud dans le JenkinsFile mais on perd la gestion des conflits
1.  Essayer de faire ce **git push force** uniquement lors de la création du dépôt et de la branche master via TravisCI

**Comment by roddet** [comment]
Je découvre à peine l'ouverture des issues :-(
J'avais déjà intégré le push force au build Jenkins.
Clever Cloud étant uniquement le résultat du déploiement d'un commit, la gestion des conflits aura lieu côté Github (sans push force).
Je pense qu'on ne perd rien en restant ainsi.
Qu'en penses-tu ?

**Comment by rguillome** [comment]
Pas de soucis Rossy, j'ai aussi le problème des notifications github qui pour moi sont un gros point noir de l'outil :)

C'est plus en termes de philosophie et de sécurité que je posais la problématique du `git push force` sur clever mais oui tu as raison, normalement avec le processus, c'est géré via Github !
